name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
     NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
     NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL= ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
